backend1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('is_newyear/',include("is_newyear.urls")),
    path('task/',include('task.urls')),
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.hello,name="hello"),
    path("<str:name>",views.greet,name="greet"),
]

is_newyear/urls.py
from django.urls import path
from . import views

app_name = "new"

urlpatterns = [ 
    path("",views.index,name="index"),
]

task/urls.py
from django.urls import path
from . import views


app_name = "task"
urlpatterns = [
    path("",views.index,name="index"),
    path("add/",views.add,name="add"),
]

hello/models.py
from django.db import models

# Create your models here.

is_newyear/models.py
from django.db import models

# Create your models here.

task/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def greet(request,name):
    return render(request,"hello/greet.html",{
        "name":name.capitalize()
    })

def hello(request):
    return render(request,"hello/index.html")

is_newyear/views.py
from django.shortcuts import render
from django.http import HttpRequest

import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear": now.date==1 and now.month==1
        # "newyear" : True
    })

task/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms

tasks = []


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")


def index(request):
    return render(request, "task/index.html", {"tasks": tasks})


def add(request):
    print(tasks)
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task6 = form.cleaned_data["task"]
            tasks.append(task6)
            return render(request, "task/index.html", {"tasks": tasks})
        else:
            form = NewTaskForm()
            return render(request, "task/add.html", {"form": form})     

    return render(request, "task/add.html", {"form": NewTaskForm()})

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>greet</title>
    </head>
    <body>
        <h2>hello {{ name }}</h2>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>hello</title>
    </head>
    <body>
        <h2>hello world!</h2>
    </body>
</html>

is_newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>newyear</title>
        <link rel="stylesheet" href="{% static 'newyear/style.css'%}">
    </head>
    <body>
        {% if newyear%}
            <h2>YES</h2>
        {% else %}
            <h2>no</h2>
        {% endif %}
    </body>
</html>

task/templates/task/add.html
{%extends 'task/layout.html'%}

{% block body %}
<h3>add task</h3>
<form action="{% url 'task:add' %}" method="post">
    {% csrf_token %}
    <input type="text" name="task">
    <input type="submit">
</form>
<a href="{% url 'task:index' %}">view tasks</a>
{% endblock %}

task/templates/task/index.html
{% extends 'task/layout.html' %}

{% block body%}
<ul>
    {% for task in tasks%}
        <li>{{ task }}</li>
    {% endfor %}
</ul>
<a href="{% url 'task:add' %}">add a new task</a>
{% endblock %}

task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>layout</title>
</head>
<body>
    {% block body%}
    {% endblock%}
</body>
</html>